services:

  backend:
    container_name: app_backend
    image: app
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/app
      - media:/app/media/
      - staticfiles:/app/staticfiles/
    command: bin/run.sh
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file: .env
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health_check/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    security_opt:
      - no-new-privileges:true

volumes:
  media:
    driver: local
  staticfiles:
    driver: local

networks:
  app_network:
    name: app_network
    driver: bridge
    ipam:
      driver: default
