services:

  backend:
    container_name: app_backend
    image: app
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - .:/app
      - media:/app/media/
      - staticfiles:/app/staticfiles/
    command: >
      bash -c " python manage.py migrate --settings=app.settings.docker
      && python manage.py collectstatic --noinput
      && gunicorn --worker 4 --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=app.settings.docker --timeout 120 --keep-alive 5 app.wsgi:application --reload"
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file: .env
    networks:
      - app_network

volumes:
  media:
    driver: local
  staticfiles:
    driver: local

networks:
  app_network:
    name: app_network
    driver: bridge
    ipam:
      driver: default
